// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ganubwsifvjraqsawccl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhbnVid3NpZnZqcmFxc2F3Y2NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTIwNDYsImV4cCI6MjA3MDY2ODA0Nn0.LVR-p1suNn0n1fWVJMaVlKhcQusqAcJmfw1C1Uh-x5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});